import React from 'react';
import { ThermalInputs, ThermalResults } from '../types';
import { X, Download, FileText, CheckCircle2 } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  inputs: ThermalInputs;
  results: ThermalResults;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, inputs, results }) => {
  if (!isOpen || !results.valid) return null;

  const reportText = `
================================================================================
heaterellaxx | HEAT EXCHANGER THERMAL CALCULATION REPORT
================================================================================
Date: ${new Date().toLocaleString()}
Flow Configuration: ${inputs.flowConfig}
Material Preset: ${inputs.materialPreset}

--------------------------------------------------------------------------------
1. OPERATING PARAMETERS
--------------------------------------------------------------------------------
Hot Fluid Inlet Temperature (T_h_in)  : ${inputs.THIn}°C
Hot Fluid Outlet Temperature (T_h_out) : ${inputs.THOut}°C
Cold Fluid Inlet Temperature (T_c_in) : ${inputs.TCIn}°C
Hot Fluid Mass Flow Rate (m_dot_h)     : ${inputs.MDotH} kg/s (Cp = ${inputs.CpH} kJ/kg·K)
Cold Fluid Mass Flow Rate (m_dot_c)    : ${inputs.MDotC} kg/s (Cp = ${inputs.CpC} kJ/kg·K)
Overall Heat Transfer Coeff (U)        : ${inputs.U} W/m²·K

--------------------------------------------------------------------------------
2. CALCULATED THERMAL PERFORMANCE RESULTS
--------------------------------------------------------------------------------
Total Heat Duty Rate (Q)               : ${results.Q_kW.toFixed(2)} kW (${(results.Q_kW/1000).toFixed(3)} MW)
Calculated Cold Fluid Outlet (T_c_out) : ${results.TCOut.toFixed(1)}°C
Temperature Difference ΔT1             : ${results.deltaT1.toFixed(2)}°C
Temperature Difference ΔT2             : ${results.deltaT2.toFixed(2)}°C
Log Mean Temperature Diff (LMTD)       : ${results.LMTD.toFixed(2)}°C
Required Heat Surface Area (A)         : ${results.area.toFixed(2)} m²
Heat Capacity Rate Ratio (Cr)          : ${results.Cr.toFixed(3)}
Exchanger Effectiveness (ε)            : ${results.effectiveness.toFixed(1)}%
Number of Transfer Units (NTU)         : ${results.NTU.toFixed(2)}

================================================================================
heaterellaxx - Heat Exchanger Engineering Engine
`.trim();

  const handleDownload = () => {
    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `heaterellaxx_report_${inputs.flowConfig}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white border-2 border-[#DDA7A5] rounded-2xl max-w-2xl w-full p-6 shadow-2xl relative space-y-4">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-lg bg-[#FFF5F7] text-gray-500 hover:text-[#C2185B] transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-2 text-[#C2185B]">
          <FileText className="w-6 h-6" />
          <h3 className="text-xl font-black text-[#2C2C2C]">Thermal Engineering Report</h3>
        </div>

        <p className="text-xs text-gray-600">
          Full technical calculation summary generated by <strong>heaterellaxx Engine</strong>.
        </p>

        <pre className="bg-[#2C2C2C] text-[#F4C2C2] font-mono text-xs p-4 rounded-xl max-h-80 overflow-y-auto border border-[#DDA7A5]/50 whitespace-pre-wrap">
          {reportText}
        </pre>

        <div className="flex justify-end gap-3 pt-2">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg text-xs font-semibold bg-gray-100 hover:bg-gray-200 text-gray-700 transition-colors"
          >
            Close
          </button>
          <button
            onClick={handleDownload}
            className="px-5 py-2 rounded-lg text-xs font-bold bg-[#C2185B] hover:bg-[#AD1457] text-white flex items-center gap-1.5 transition-colors shadow-md"
          >
            <Download className="w-4 h-4" />
            <span>Download Report</span>
          </button>
        </div>
      </div>
    </div>
  );
};
