import React, { useState } from 'react';
import { ThermalInputs, ThermalResults } from '../types';
import { Calculator, BookOpen, CheckCircle2, Copy, Check, Sparkles, ShieldCheck, Flame, Cpu } from 'lucide-react';
import { KatexMath } from './KatexMath';

interface GoverningEquationsProps {
  inputs: ThermalInputs;
  results: ThermalResults;
}

type ProofTab = 'all' | 'duty' | 'lmtd' | 'area' | 'ntu' | 'second_law' | 'derivation' | 'latex_code';

export const GoverningEquations: React.FC<GoverningEquationsProps> = ({ inputs, results }) => {
  const [activeProof, setActiveProof] = useState<ProofTab>('all');
  const [copiedLatex, setCopiedLatex] = useState(false);

  if (!results.valid) return null;

  const rawLatexDocument = `
% Academic Heat Exchanger Sizing & Performance Formulation
% Generated by heaterellaxx Thermal Engineering Suite
\\documentclass{article}
\\usepackage{amsmath,amssymb}

\\begin{document}
\\section*{Thermodynamic Analysis of ${inputs.flowConfig} Heat Exchanger}

\\subsection*{1. First Law Heat Duty Balance}
\\begin{equation}
Q = \\dot{m}_h C_{p,h} (T_{h,\\text{in}} - T_{h,\\text{out}}) = \\dot{m}_c C_{p,c} (T_{c,\\text{out}} - T_{c,\\text{in}})
\\end{equation}
Given: $\\dot{m}_h = ${inputs.MDotH.toFixed(2)}\\text{ kg/s}$, $C_{p,h} = ${inputs.CpH.toFixed(2)}\\text{ kJ/kg}\\cdot\\text{K}$, $T_{h,\\text{in}} = ${inputs.THIn.toFixed(1)}^\\circ\\text{C}$, $T_{h,\\text{out}} = ${inputs.THOut.toFixed(1)}^\\circ\\text{C}$
\\begin{equation}
Q = ${inputs.MDotH.toFixed(2)} \\times ${inputs.CpH.toFixed(2)} \\times (${inputs.THIn.toFixed(1)} - ${inputs.THOut.toFixed(1)}) = ${results.Q_kW.toFixed(2)}\\text{ kW}
\\end{equation}
Coolant outlet temperature:
\\begin{equation}
T_{c,\\text{out}} = T_{c,\\text{in}} + \\frac{Q}{\\dot{m}_c C_{p,c}} = ${inputs.TCIn.toFixed(1)} + \\frac{${results.Q_kW.toFixed(2)}}{${inputs.MDotC.toFixed(2)} \\times ${inputs.CpC.toFixed(3)}} = ${results.TCOut.toFixed(2)}^\\circ\\text{C}
\\end{equation}

\\subsection*{2. Log Mean Temperature Difference (LMTD)}
Terminal differences for ${inputs.flowConfig}:
\\begin{equation}
\\Delta T_1 = ${results.deltaT1.toFixed(2)}^\\circ\\text{C}, \\quad \\Delta T_2 = ${results.deltaT2.toFixed(2)}^\\circ\\text{C}
\\end{equation}
\\begin{equation}
\\text{LMTD} = \\frac{\\Delta T_1 - \\Delta T_2}{\\ln(\\Delta T_1 / \\Delta T_2)} = \\frac{${results.deltaT1.toFixed(2)} - ${results.deltaT2.toFixed(2)}}{\\ln(${results.deltaT1.toFixed(2)} / ${results.deltaT2.toFixed(2)})} = ${results.LMTD.toFixed(2)}^\\circ\\text{C}
\\end{equation}

\\subsection*{3. Required Heat Transfer Area}
\\begin{equation}
A = \\frac{Q}{U \\cdot \\text{LMTD}} = \\frac{${(results.Q_kW * 1000).toFixed(1)}\\text{ W}}{${inputs.U}\\text{ W/m}^2\\cdot\\text{K} \\times ${results.LMTD.toFixed(2)}^\\circ\\text{C}} = ${results.area.toFixed(2)}\\text{ m}^2
\\end{equation}

\\subsection*{4. $\\varepsilon$-NTU Method}
\\begin{equation}
C_{\\min} = ${results.Cmin.toFixed(2)}\\text{ kW/K}, \\quad Q_{\\max} = ${results.QMax.toFixed(2)}\\text{ kW}, \\quad \\varepsilon = ${results.effectiveness.toFixed(1)}\\%, \\quad \\text{NTU} = ${results.NTU.toFixed(2)}
\\end{equation}

\\subsection*{5. Second Law Entropy Generation}
\\begin{equation}
\\dot{S}_{\\text{gen}} = \\dot{m}_h C_{p,h} \\ln\\left(\\frac{T_{h,\\text{out}}}{T_{h,\\text{in}}}\\right) + \\dot{m}_c C_{p,c} \\ln\\left(\\frac{T_{c,\\text{out}}}{T_{c,\\text{in}}}\\right) = ${results.S_gen_kW_K.toFixed(4)}\\text{ kW/K} \\ge 0
\\end{equation}
\\end{document}
  `.trim();

  const handleCopyLatex = () => {
    navigator.clipboard.writeText(rawLatexDocument);
    setCopiedLatex(true);
    setTimeout(() => setCopiedLatex(false), 2000);
  };

  return (
    <div className="bg-white border-2 border-[#E8B4B8] rounded-2xl shadow-sm overflow-hidden transition-all">
      {/* Header Bar */}
      <div className="p-6 bg-gradient-to-r from-[#FFF0F3] via-white to-[#FFF5F7] border-b border-[#E8B4B8]/70 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-[#C2185B] text-white rounded-xl shadow-sm">
            <Calculator className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-lg font-extrabold text-[#9C1545] tracking-tight">
                Thermodynamic Governing Equations & Analytical Proofs
              </h3>
              <span className="px-2.5 py-0.5 text-[11px] font-bold bg-[#C2185B]/10 text-[#C2185B] rounded-full border border-[#C2185B]/20">
                1st & 2nd Law Proofs
              </span>
            </div>
            <p className="text-xs text-gray-600 mt-0.5">
              Live variable substitutions, analytical calculus derivations, and Overleaf LaTeX code export
            </p>
          </div>
        </div>

        {/* Proof Filter Tabs */}
        <div className="flex flex-wrap items-center gap-1.5 p-1 bg-white border border-[#E8B4B8] rounded-xl shadow-xs self-start md:self-auto overflow-x-auto">
          <button
            onClick={() => setActiveProof('all')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeProof === 'all'
                ? 'bg-[#C2185B] text-white shadow-xs'
                : 'text-gray-600 hover:text-[#9C1545] hover:bg-[#FFF0F3]'
            }`}
          >
            All Proofs
          </button>
          <button
            onClick={() => setActiveProof('duty')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeProof === 'duty'
                ? 'bg-[#C2185B] text-white shadow-xs'
                : 'text-gray-600 hover:text-[#9C1545] hover:bg-[#FFF0F3]'
            }`}
          >
            1. Duty (Q)
          </button>
          <button
            onClick={() => setActiveProof('lmtd')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeProof === 'lmtd'
                ? 'bg-[#C2185B] text-white shadow-xs'
                : 'text-gray-600 hover:text-[#9C1545] hover:bg-[#FFF0F3]'
            }`}
          >
            2. LMTD (ΔT_lm)
          </button>
          <button
            onClick={() => setActiveProof('area')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeProof === 'area'
                ? 'bg-[#C2185B] text-white shadow-xs'
                : 'text-gray-600 hover:text-[#9C1545] hover:bg-[#FFF0F3]'
            }`}
          >
            3. Sizing (A)
          </button>
          <button
            onClick={() => setActiveProof('ntu')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeProof === 'ntu'
                ? 'bg-[#C2185B] text-white shadow-xs'
                : 'text-gray-600 hover:text-[#9C1545] hover:bg-[#FFF0F3]'
            }`}
          >
            4. ε-NTU
          </button>
          <button
            onClick={() => setActiveProof('second_law')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeProof === 'second_law'
                ? 'bg-[#C2185B] text-white shadow-xs'
                : 'text-gray-600 hover:text-[#9C1545] hover:bg-[#FFF0F3]'
            }`}
          >
            5. Second Law & Exergy
          </button>
          <button
            onClick={() => setActiveProof('derivation')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeProof === 'derivation'
                ? 'bg-[#1E1E1E] text-[#F4C2C2] shadow-xs'
                : 'text-gray-600 hover:text-[#9C1545] hover:bg-[#FFF0F3]'
            }`}
          >
            Calculus Derivation
          </button>
          <button
            onClick={() => setActiveProof('latex_code')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeProof === 'latex_code'
                ? 'bg-[#C2185B] text-white shadow-xs'
                : 'text-gray-600 hover:text-[#9C1545] hover:bg-[#FFF0F3]'
            }`}
          >
            LaTeX Code Export
          </button>
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* 1. Heat Duty Rate Equations */}
        {(activeProof === 'all' || activeProof === 'duty') && (
          <div className="bg-[#FFF8F9] border-2 border-[#E8B4B8]/80 rounded-2xl p-5 space-y-4 hover:border-[#C2185B]/60 transition-all">
            <div className="flex items-center justify-between border-b border-[#E8B4B8]/60 pb-3">
              <div className="flex items-center gap-2">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-[#9C1545] text-white text-xs font-extrabold">
                  1
                </span>
                <span className="text-sm font-extrabold text-[#9C1545] tracking-wide uppercase">
                  First Law Heat Duty Balance Equations (Q)
                </span>
              </div>
              <span className="text-xs font-mono font-bold text-[#9C1545] bg-white px-2.5 py-1 rounded-lg border border-[#E8B4B8] shadow-xs">
                Q = {results.Q_kW.toFixed(2)} kW
              </span>
            </div>

            {/* LaTeX Formula Block */}
            <div className="bg-white p-4 rounded-xl border border-[#E8B4B8] shadow-xs flex flex-col items-center justify-center gap-2">
              <p className="text-[11px] font-semibold text-gray-500 uppercase tracking-widest self-start">
                Governing First Law Energy Conservation:
              </p>
              <KatexMath
                math="Q = \dot{m}_h \cdot C_{p,h} \cdot \left(T_{h,\text{in}} - T_{h,\text{out}}\right) = \dot{m}_c \cdot C_{p,c} \cdot \left(T_{c,\text{out}} - T_{c,\text{in}}\right)"
                block
                className="text-sm sm:text-base font-bold text-[#1E1E1E]"
              />
            </div>

            {/* Live Step-by-Step Substitution */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-1">
              <div className="p-3.5 bg-white rounded-xl border border-gray-200 text-xs text-[#1E1E1E] space-y-1.5">
                <div className="flex items-center gap-1.5 font-bold text-[#9C1545]">
                  <CheckCircle2 className="w-3.5 h-3.5 text-[#15803D]" />
                  <span>Hot Fluid Heat Release:</span>
                </div>
                <div className="bg-[#FFF5F7] p-2 rounded border border-[#E8B4B8]/50 overflow-x-auto">
                  <KatexMath
                    math={`Q = (${inputs.MDotH.toFixed(2)}\\text{ kg/s}) \\times (${inputs.CpH.toFixed(2)}\\text{ kJ/kg}\\cdot\\text{K}) \\times (${inputs.THIn.toFixed(1)} - ${inputs.THOut.toFixed(1)})^\\circ\\text{C}`}
                  />
                </div>
                <p className="text-gray-700 font-medium">
                  Result: <strong className="text-[#9C1545]">{results.Q_kW.toFixed(2)} kW</strong> ({(results.Q_kW / 1000).toFixed(3)} MW)
                </p>
              </div>

              <div className="p-3.5 bg-white rounded-xl border border-gray-200 text-xs text-[#1E1E1E] space-y-1.5">
                <div className="flex items-center gap-1.5 font-bold text-[#9C1545]">
                  <CheckCircle2 className="w-3.5 h-3.5 text-[#15803D]" />
                  <span>Cold Fluid Temperature Rise:</span>
                </div>
                <div className="bg-[#FFF5F7] p-2 rounded border border-[#E8B4B8]/50 overflow-x-auto">
                  <KatexMath
                    math={`T_{c,\\text{out}} = ${inputs.TCIn.toFixed(1)} + \\frac{${results.Q_kW.toFixed(2)}}{${inputs.MDotC.toFixed(2)} \\times ${inputs.CpC.toFixed(3)}} = ${results.TCOut.toFixed(2)}^\\circ\\text{C}`}
                  />
                </div>
                <p className="text-gray-700 font-medium">
                  Coolant Heating Delta: <strong className="text-[#0284C7]">+{(results.TCOut - inputs.TCIn).toFixed(2)}°C</strong>
                </p>
              </div>
            </div>
          </div>
        )}

        {/* 2. LMTD Formulations */}
        {(activeProof === 'all' || activeProof === 'lmtd') && (
          <div className="bg-[#FFF8F9] border-2 border-[#E8B4B8]/80 rounded-2xl p-5 space-y-4 hover:border-[#C2185B]/60 transition-all">
            <div className="flex items-center justify-between border-b border-[#E8B4B8]/60 pb-3">
              <div className="flex items-center gap-2">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-[#9C1545] text-white text-xs font-extrabold">
                  2
                </span>
                <span className="text-sm font-extrabold text-[#9C1545] tracking-wide uppercase">
                  Terminal Temperature Differences & Log Mean Driving Force (LMTD)
                </span>
              </div>
              <span className="text-xs font-mono font-bold text-[#9C1545] bg-white px-2.5 py-1 rounded-lg border border-[#E8B4B8] shadow-xs">
                ΔT_lm = {results.LMTD.toFixed(2)} °C
              </span>
            </div>

            <div className="bg-white p-4 rounded-xl border border-[#E8B4B8] shadow-xs flex flex-col items-center justify-center gap-2">
              <p className="text-[11px] font-semibold text-gray-500 uppercase tracking-widest self-start">
                Effective Thermal Driving Potential:
              </p>
              <KatexMath
                math="\text{LMTD} = \Delta T_{lm} = \frac{\Delta T_1 - \Delta T_2}{\ln\left(\frac{\Delta T_1}{\Delta T_2}\right)}"
                block
                className="text-sm sm:text-base font-bold text-[#1E1E1E]"
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-1">
              <div className="p-3.5 bg-white rounded-xl border border-gray-200 text-xs text-[#1E1E1E] space-y-1.5">
                <span className="font-bold text-[#9C1545]">
                  Active Flow Mode: {inputs.flowConfig}
                </span>
                <div className="bg-[#FFF5F7] p-2 rounded border border-[#E8B4B8]/50 overflow-x-auto space-y-1">
                  {inputs.flowConfig === 'Counterflow' ? (
                    <>
                      <div><KatexMath math={`\\Delta T_1 = T_{h,\\text{in}} - T_{c,\\text{out}} = ${inputs.THIn.toFixed(1)} - ${results.TCOut.toFixed(2)} = ${results.deltaT1.toFixed(2)}^\\circ\\text{C}`} /></div>
                      <div><KatexMath math={`\\Delta T_2 = T_{h,\\text{out}} - T_{c,\\text{in}} = ${inputs.THOut.toFixed(1)} - ${inputs.TCIn.toFixed(1)} = ${results.deltaT2.toFixed(2)}^\\circ\\text{C}`} /></div>
                    </>
                  ) : (
                    <>
                      <div><KatexMath math={`\\Delta T_1 = T_{h,\\text{in}} - T_{c,\\text{in}} = ${inputs.THIn.toFixed(1)} - ${inputs.TCIn.toFixed(1)} = ${results.deltaT1.toFixed(2)}^\\circ\\text{C}`} /></div>
                      <div><KatexMath math={`\\Delta T_2 = T_{h,\\text{out}} - T_{c,\\text{out}} = ${inputs.THOut.toFixed(1)} - ${results.TCOut.toFixed(2)} = ${results.deltaT2.toFixed(2)}^\\circ\\text{C}`} /></div>
                    </>
                  )}
                </div>
              </div>

              <div className="p-3.5 bg-white rounded-xl border border-gray-200 text-xs text-[#1E1E1E] space-y-1.5">
                <span className="font-bold text-[#9C1545]">
                  Logarithmic Mean Resolution:
                </span>
                <div className="bg-[#FFF5F7] p-2 rounded border border-[#E8B4B8]/50 overflow-x-auto">
                  <KatexMath
                    math={`\\text{LMTD} = \\frac{${results.deltaT1.toFixed(2)} - ${results.deltaT2.toFixed(2)}}{\\ln\\left(\\frac{${results.deltaT1.toFixed(2)}}{${results.deltaT2.toFixed(2)}}\\right)} = ${results.LMTD.toFixed(2)}^\\circ\\text{C}`}
                  />
                </div>
                <p className="text-gray-700 font-medium">
                  Driving Temperature Potential: <strong>{results.LMTD.toFixed(2)}°C</strong>
                </p>
              </div>
            </div>
          </div>
        )}

        {/* 3. Surface Area & Sizing */}
        {(activeProof === 'all' || activeProof === 'area') && (
          <div className="bg-[#FFF8F9] border-2 border-[#E8B4B8]/80 rounded-2xl p-5 space-y-4 hover:border-[#C2185B]/60 transition-all">
            <div className="flex items-center justify-between border-b border-[#E8B4B8]/60 pb-3">
              <div className="flex items-center gap-2">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-[#9C1545] text-white text-xs font-extrabold">
                  3
                </span>
                <span className="text-sm font-extrabold text-[#9C1545] tracking-wide uppercase">
                  Heat Transfer Surface Area Requirement (A)
                </span>
              </div>
              <span className="text-xs font-mono font-bold text-[#9C1545] bg-white px-2.5 py-1 rounded-lg border border-[#E8B4B8] shadow-xs">
                A = {results.area.toFixed(2)} m²
              </span>
            </div>

            <div className="bg-white p-4 rounded-xl border border-[#E8B4B8] shadow-xs flex flex-col items-center justify-center gap-2">
              <p className="text-[11px] font-semibold text-gray-500 uppercase tracking-widest self-start">
                Required Exchanger Area Relation:
              </p>
              <KatexMath
                math="A = \frac{Q}{U \cdot \text{LMTD}} = \frac{Q_{\text{watts}}}{U \cdot \Delta T_{lm}} \quad [\text{m}^2]"
                block
                className="text-sm sm:text-base font-bold text-[#1E1E1E]"
              />
            </div>

            <div className="p-3.5 bg-white rounded-xl border border-gray-200 text-xs text-[#1E1E1E] space-y-2">
              <span className="font-bold text-[#9C1545]">
                Engineering Computation:
              </span>
              <div className="bg-[#FFF5F7] p-2.5 rounded border border-[#E8B4B8]/50 overflow-x-auto">
                <KatexMath
                  math={`A = \\frac{(${results.Q_kW.toFixed(2)} \\times 10^3\\text{ W})}{(${inputs.U}\\text{ W/m}^2\\cdot\\text{K}) \\times (${results.LMTD.toFixed(2)}^\\circ\\text{C})} = \\mathbf{${results.area.toFixed(2)}\\text{ m}^2}`}
                  block
                />
              </div>
              <p className="text-gray-700 text-center font-medium pt-1">
                With overall conductance <KatexMath math={`U = ${inputs.U}\\text{ W/m}^2\\cdot\\text{K}`} />, the bundle requires <strong className="text-[#9C1545]">{results.area.toFixed(2)} m²</strong> ({(results.area * 10.7639).toFixed(1)} sq ft) of effective contact area.
              </p>
            </div>
          </div>
        )}

        {/* 4. ε-NTU Effectiveness Method */}
        {(activeProof === 'all' || activeProof === 'ntu') && (
          <div className="bg-[#FFF8F9] border-2 border-[#E8B4B8]/80 rounded-2xl p-5 space-y-4 hover:border-[#C2185B]/60 transition-all">
            <div className="flex items-center justify-between border-b border-[#E8B4B8]/60 pb-3">
              <div className="flex items-center gap-2">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-[#9C1545] text-white text-xs font-extrabold">
                  4
                </span>
                <span className="text-sm font-extrabold text-[#9C1545] tracking-wide uppercase">
                  Number of Transfer Units (NTU) & Effectiveness (ε) Method
                </span>
              </div>
              <span className="text-xs font-mono font-bold text-[#9C1545] bg-white px-2.5 py-1 rounded-lg border border-[#E8B4B8] shadow-xs">
                ε = {results.effectiveness.toFixed(1)}% | NTU = {results.NTU.toFixed(2)}
              </span>
            </div>

            <div className="bg-white p-4 rounded-xl border border-[#E8B4B8] shadow-xs space-y-2">
              <KatexMath
                math="C_{\min} = \min\left(\dot{m}_h C_{p,h}, \dot{m}_c C_{p,c}\right), \quad Q_{\max} = C_{\min}\left(T_{h,\text{in}} - T_{c,\text{in}}\right)"
                block
                className="text-xs sm:text-sm font-bold text-[#1E1E1E]"
              />
              <KatexMath
                math="\varepsilon = \frac{Q}{Q_{\max}} \times 100\%, \quad \text{NTU} = \frac{U \cdot A}{C_{\min} \times 1000}, \quad C_r = \frac{C_{\min}}{C_{\max}}"
                block
                className="text-xs sm:text-sm font-bold text-[#1E1E1E]"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
              <div className="p-3 bg-white rounded-xl border border-gray-200 text-xs text-center space-y-1">
                <span className="text-gray-500 font-semibold uppercase text-[10px]">Min Heat Capacity</span>
                <p className="font-bold text-[#9C1545] text-sm">
                  <KatexMath math={`C_{\\min} = ${results.Cmin.toFixed(2)}\\text{ kW/K}`} />
                </p>
                <p className="text-[11px] text-gray-600">Side: {results.Ch < results.Cc ? 'Hot Fluid Side' : 'Cold Fluid Side'}</p>
              </div>

              <div className="p-3 bg-white rounded-xl border border-gray-200 text-xs text-center space-y-1">
                <span className="text-gray-500 font-semibold uppercase text-[10px]">Maximum Possible Heat</span>
                <p className="font-bold text-[#9C1545] text-sm">
                  <KatexMath math={`Q_{\\max} = ${results.QMax.toFixed(2)}\\text{ kW}`} />
                </p>
                <p className="text-[11px] text-gray-600">Infinite Area Thermodynamic Limit</p>
              </div>

              <div className="p-3 bg-white rounded-xl border border-gray-200 text-xs text-center space-y-1">
                <span className="text-gray-500 font-semibold uppercase text-[10px]">Capacity Ratio</span>
                <p className="font-bold text-[#9C1545] text-sm">
                  <KatexMath math={`C_r = ${results.Cr.toFixed(3)}`} />
                </p>
                <p className="text-[11px] text-gray-600">Dimensionless</p>
              </div>
            </div>
          </div>
        )}

        {/* 5. Second Law & Exergy */}
        {(activeProof === 'all' || activeProof === 'second_law') && (
          <div className="bg-[#FFF8F9] border-2 border-[#E8B4B8]/80 rounded-2xl p-5 space-y-4 hover:border-[#C2185B]/60 transition-all">
            <div className="flex items-center justify-between border-b border-[#E8B4B8]/60 pb-3">
              <div className="flex items-center gap-2">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-[#9C1545] text-white text-xs font-extrabold">
                  5
                </span>
                <span className="text-sm font-extrabold text-[#9C1545] tracking-wide uppercase">
                  Second Law of Thermodynamics & Exergetic Efficiency
                </span>
              </div>
              <span className="text-xs font-mono font-bold text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded-lg border border-emerald-300 shadow-xs flex items-center gap-1">
                <ShieldCheck className="w-3.5 h-3.5" /> Entropy Generation Verified
              </span>
            </div>

            <div className="bg-white p-4 rounded-xl border border-[#E8B4B8] shadow-xs space-y-2">
              <p className="text-[11px] font-semibold text-gray-500 uppercase tracking-widest">
                Clausius-Kelvin Second Law Rate Formulation:
              </p>
              <KatexMath
                math="\dot{S}_{\text{gen}} = \dot{m}_h C_{p,h} \ln\left(\frac{T_{h,\text{out}}}{T_{h,\text{in}}}\right) + \dot{m}_c C_{p,c} \ln\left(\frac{T_{c,\text{out}}}{T_{c,\text{in}}}\right) \ge 0"
                block
                className="text-xs sm:text-sm font-bold text-[#1E1E1E]"
              />
              <KatexMath
                math="\dot{E}_{x,\text{dest}} = T_0 \cdot \dot{S}_{\text{gen}} \quad (T_0 = 298.15\text{ K}), \quad \eta_{\text{ex}} = \frac{\dot{E}_{x,\text{cold,gain}}}{\dot{E}_{x,\text{hot,loss}}} \times 100\%"
                block
                className="text-xs sm:text-sm font-bold text-[#1E1E1E]"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
              <div className="p-3 bg-white rounded-xl border border-gray-200 text-xs text-center space-y-1">
                <span className="text-gray-500 font-semibold uppercase text-[10px]">Entropy Generation Rate</span>
                <p className="font-bold text-[#9C1545] text-sm">
                  <KatexMath math={`\\dot{S}_{\\text{gen}} = ${results.S_gen_kW_K.toFixed(4)}\\text{ kW/K}`} />
                </p>
                <p className="text-[11px] text-emerald-700 font-bold">≥ 0 (Second Law Obeyed)</p>
              </div>

              <div className="p-3 bg-white rounded-xl border border-gray-200 text-xs text-center space-y-1">
                <span className="text-gray-500 font-semibold uppercase text-[10px]">Exergy Destroyed Rate</span>
                <p className="font-bold text-[#9C1545] text-sm">
                  <KatexMath math={`\\dot{E}_{x,\\text{dest}} = ${results.Ex_dest_kW.toFixed(2)}\\text{ kW}`} />
                </p>
                <p className="text-[11px] text-gray-600">Gouy-Stodola Loss</p>
              </div>

              <div className="p-3 bg-white rounded-xl border border-gray-200 text-xs text-center space-y-1">
                <span className="text-gray-500 font-semibold uppercase text-[10px]">Exergetic Recovery</span>
                <p className="font-bold text-[#9C1545] text-sm">
                  <KatexMath math={`\\eta_{\\text{ex}} = ${results.exergyEfficiency.toFixed(1)}\\%`} />
                </p>
                <p className="text-[11px] text-gray-600">Second-Law Efficiency</p>
              </div>
            </div>
          </div>
        )}

        {/* 6. Analytical Calculus Derivation */}
        {(activeProof === 'all' || activeProof === 'derivation') && (
          <div className="bg-[#FFF8F9] border-2 border-[#E8B4B8]/80 rounded-2xl p-5 space-y-4 hover:border-[#C2185B]/60 transition-all">
            <div className="flex items-center justify-between border-b border-[#E8B4B8]/60 pb-3">
              <div className="flex items-center gap-2">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-[#1E1E1E] text-[#F4C2C2] text-xs font-extrabold">
                  ∫
                </span>
                <span className="text-sm font-extrabold text-[#9C1545] tracking-wide uppercase">
                  Rigorous First-Principles Derivation of LMTD
                </span>
              </div>
              <span className="text-xs font-mono font-bold bg-[#1E1E1E] text-[#F4C2C2] px-2.5 py-1 rounded-lg">
                Calculus Proof
              </span>
            </div>

            <div className="bg-white p-5 rounded-xl border border-[#E8B4B8] shadow-xs text-xs space-y-3 text-gray-800">
              <p className="leading-relaxed">
                Consider an infinitesimal control element of heat exchange surface <KatexMath math="dA" /> along the length of the bundle. The differential heat transfer rate is:
              </p>
              <div className="bg-[#FFF5F7] p-2 rounded text-center">
                <KatexMath math="dq = -\dot{m}_h C_{p,h} dT_h = \mp \dot{m}_c C_{p,c} dT_c = U \left(T_h - T_c\right) dA = U \Delta T dA" block />
              </div>
              <p className="leading-relaxed">
                Differentiating the temperature difference <KatexMath math="\Delta T = T_h - T_c" /> gives <KatexMath math="d(\Delta T) = dT_h - dT_c" />. Substituting the heat capacity rates <KatexMath math="C_h = \dot{m}_h C_{p,h}" /> and <KatexMath math="C_c = \dot{m}_c C_{p,c}" />:
              </p>
              <div className="bg-[#FFF5F7] p-2 rounded text-center">
                <KatexMath math="d(\Delta T) = -dq \left(\frac{1}{C_h} \pm \frac{1}{C_c}\right) = -U \Delta T dA \left(\frac{1}{C_h} \pm \frac{1}{C_c}\right)" block />
              </div>
              <p className="leading-relaxed">
                Separating variables and integrating along the total surface area from <KatexMath math="A = 0" /> to <KatexMath math="A" />:
              </p>
              <div className="bg-[#FFF5F7] p-2 rounded text-center">
                <KatexMath math="\int_1^2 \frac{d(\Delta T)}{\Delta T} = -U \left(\frac{1}{C_h} \pm \frac{1}{C_c}\right) \int_0^A dA \implies \ln\left(\frac{\Delta T_2}{\Delta T_1}\right) = -UA \left(\frac{1}{C_h} \pm \frac{1}{C_c}\right)" block />
              </div>
              <p className="leading-relaxed">
                From overall energy balance, <KatexMath math="Q = C_h (T_{h,\text{in}} - T_{h,\text{out}}) = C_c (T_{c,\text{out}} - T_{c,\text{in}})" />, which yields <KatexMath math="\frac{1}{C_h} \pm \frac{1}{C_c} = \frac{\Delta T_1 - \Delta T_2}{Q}" />. Substituting back:
              </p>
              <div className="bg-[#FFF5F7] p-2.5 rounded text-center font-bold text-[#9C1545]">
                <KatexMath math="Q = U A \left[\frac{\Delta T_1 - \Delta T_2}{\ln(\Delta T_1 / \Delta T_2)}\right] = U A \Delta T_{lm} \quad \blacksquare" block />
              </div>
            </div>
          </div>
        )}

        {/* 7. LaTeX Source Code Export */}
        {(activeProof === 'all' || activeProof === 'latex_code') && (
          <div className="bg-[#1E1E1E] text-white border-2 border-[#E8B4B8] rounded-2xl p-5 space-y-3">
            <div className="flex items-center justify-between border-b border-gray-800 pb-3">
              <div className="flex items-center gap-2">
                <Cpu className="w-5 h-5 text-[#F4C2C2]" />
                <span className="text-xs font-extrabold text-[#F4C2C2] uppercase tracking-wider">
                  Academic LaTeX / Overleaf Source Code
                </span>
              </div>
              <button
                onClick={handleCopyLatex}
                className="px-3 py-1.5 bg-[#C2185B] hover:bg-[#AD1457] text-white rounded-lg text-xs font-bold flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs"
              >
                {copiedLatex ? <Check className="w-3.5 h-3.5 text-emerald-300" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedLatex ? 'Copied LaTeX!' : 'Copy LaTeX Document'}</span>
              </button>
            </div>
            <p className="text-xs text-gray-400">
              Copy this compile-ready LaTeX document directly into Overleaf, TeXShop, or your academic lab report submission.
            </p>
            <pre className="p-4 bg-black/60 rounded-xl text-[11px] font-mono text-emerald-400 overflow-x-auto max-h-60 border border-gray-800">
              {rawLatexDocument}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
};
